
spring:
  h2:
    console:
      enabled: true

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        search:
          default:
            directory_provider: filesystem
            indexBase: C:/Temp

