
spring:
  h2:
    console:
      enabled: true

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        search:
          backend:
            directoroy:
              root: /path/to/my/root
            analysis:
              configurer: class:com.study.jaehun.MyLuceneAnalysisConfigurer

